version: "3"
services:
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: university_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
