CREATE TABLE lectors (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    degree text NOT NULL,
    salary numeric(12, 2) NOT NULL
);

CREATE TABLE departments (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    head_id int NOT NULL,
    FOREIGN KEY(head_id) REFERENCES lectors(id)
);

CREATE TABLE department_lectors (
    department_id int NOT NULL,
    lector_id int NOT NUll,
    FOREIGN KEY(department_id) REFERENCES departments(id),
    FOREIGN KEY(lector_id) REFERENCES lectors(id),
    CONSTRAINT unique_department_lector UNIQUE (department_id, lector_id)
);
